name: Lidarr

on:
  push:
    paths:
      - .github/workflows/lidarr.yml
      - contexts/lidarr/*
  pull_request:
    paths:
      - .github/workflows/lidarr.yml
      - contexts/lidarr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=Lidarr/Lidarr versioning=loose
  LIDARR_VERSION: "2.7.1.4417"

jobs:
  versions:
    name: Versions
    outputs:
      LIDARR_VERSION: ${{ env.LIDARR_VERSION }}
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "LIDARR_VERSION=${{ env.LIDARR_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    # We don't need to run this on Renovate PRs. We will already test the `renovate/foo` branch.
    if: github.event_name != 'pull_request' || github.actor != 'renovate[bot]'
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        LIDARR_VERSION=${{ needs.versions.outputs.LIDARR_VERSION }}
      context: contexts/lidarr
      image-description: Lidarr is a music collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new albums from your favorite artists and will interface with clients and indexers to grab, sort, and rename them. It can also be configured to automatically upgrade the quality of existing files in the library when a better quality format becomes available.
      image-name: oliversalzburg/containers/lidarr
      image-tag: ${{ needs.versions.outputs.LIDARR_VERSION }}
      image-title: Lidarr
      is-latest: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: build-publish
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  delete-untagged:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    name: Clean up layers
    needs: qa-successful
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Delete untagged layers
        uses: Chizkiyahu/delete-untagged-ghcr-action@e8c780ca2d589797e657691fc16bffe066714890 # v4
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: containers/lidarr
          untagged_only: true
          owner_type: user
