name: Prowlarr

on:
  push:
    paths:
      - .github/workflows/prowlarr.yml
      - contexts/prowlarr/*
  pull_request:
    paths:
      - .github/workflows/prowlarr.yml
      - contexts/prowlarr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=Prowlarr/Prowlarr versioning=loose
  PROWLARR_VERSION: "1.28.2.4885"

jobs:
  versions:
    name: Versions
    outputs:
      PROWLARR_VERSION: ${{ env.PROWLARR_VERSION }}
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "PROWLARR_VERSION=${{ env.PROWLARR_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        PROWLARR_VERSION=${{ needs.versions.outputs.PROWLARR_VERSION }}
      context: contexts/prowlarr
      image-description: The Ultimate Indexer Manager
      image-name: oliversalzburg/containers/prowlarr
      image-tag: ${{ needs.versions.outputs.PROWLARR_VERSION }}
      image-title: Prowlarr
      is-latest: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: build-publish
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
