name: qBittorrent

on:
  push:
    paths:
      - .github/workflows/qbittorrent.yml
      - contexts/qbittorrent/*
  pull_request:
    paths:
      - .github/workflows/qbittorrent.yml
      - contexts/qbittorrent/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-tags depName=qbittorrent/qBittorrent extractVersion=^release-(?<version>.*)$
  QBITTORRENT_VERSION: "4.6.7"

jobs:
  versions:
    name: Versions
    outputs:
      QBITTORRENT_VERSION: ${{ env.QBITTORRENT_VERSION }}
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "QBITTORRENT_VERSION=${{ env.QBITTORRENT_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    # We don't need to run this on Renovate PRs. We will already test the `renovate/foo` branch.
    if: github.event_name != 'pull_request' || github.actor != 'renovate[bot]'
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        QBITTORRENT_VERSION=${{ needs.versions.outputs.QBITTORRENT_VERSION }}
      context: contexts/qbittorrent
      image-description: The qBittorrent project aims to provide an open-source software alternative to µTorrent.
      image-name: oliversalzburg/containers/qbittorrent
      image-tag: ${{ needs.versions.outputs.QBITTORRENT_VERSION }}
      image-title: qBittorrent
      is-latest: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  test:
    name: Test
    needs: 
      - versions
      - build-publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run container with image
        run: |
          .scripts/test.sh podman run --rm ghcr.io/oliversalzburg/containers/qbittorrent:${{ needs.versions.outputs.QBITTORRENT_VERSION }}

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: 
      - build-publish
      - test
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  delete-untagged:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    name: Clean up layers
    needs: qa-successful
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Delete untagged layers
        uses: Chizkiyahu/delete-untagged-ghcr-action@e8c780ca2d589797e657691fc16bffe066714890 # v4
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: containers/qbittorrent
          untagged_only: true
          owner_type: user
