name: Radarr

on:
  push:
    paths:
      - .github/workflows/radarr.yml
      - contexts/radarr/*
  pull_request:
    paths:
      - .github/workflows/radarr.yml
      - contexts/radarr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=Radarr/Radarr versioning=loose
  RADARR_VERSION: "5.24.1.10017"

jobs:
  versions:
    name: Versions
    outputs:
      RADARR_VERSION: ${{ env.RADARR_VERSION }}
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "RADARR_VERSION=${{ env.RADARR_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        RADARR_VERSION=${{ needs.versions.outputs.RADARR_VERSION }}
      context: contexts/radarr
      dist-tag: latest
      image-description: Works great and looks even better doing it.
      image-name: oliversalzburg/containers/radarr
      image-tag: v${{ needs.versions.outputs.RADARR_VERSION }}
      image-title: Radarr
      is-latest: true
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: build-publish
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
