name: Radarr

on:
  push:
    paths:
      - .github/workflows/radarr.yml
      - contexts/radarr/*
  pull_request:
    paths:
      - .github/workflows/radarr.yml
      - contexts/radarr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=Radarr/Radarr versioning=loose
  RADARR_VERSION: "5.13.1.9378"

jobs:
  versions:
    name: Versions
    outputs:
      RADARR_VERSION: ${{ env.RADARR_VERSION }}
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "RADARR_VERSION=${{ env.RADARR_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    # We don't need to run this on Renovate PRs. We will already test the `renovate/foo` branch.
    if: github.event_name != 'pull_request' || github.actor != 'renovate[bot]'
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        RADARR_VERSION=${{ needs.versions.outputs.RADARR_VERSION }}
      context: contexts/radarr
      image-description: Works great and looks even better doing it.
      image-name: oliversalzburg/containers/radarr
      image-tag: ${{ needs.versions.outputs.RADARR_VERSION }}
      image-title: Radarr
      is-latest: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: build-publish
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  delete-untagged:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    name: Clean up layers
    needs: qa-successful
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Delete untagged layers
        uses: Chizkiyahu/delete-untagged-ghcr-action@e8c780ca2d589797e657691fc16bffe066714890 # v4
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: containers/radarr
          untagged_only: true
          owner_type: user
