name: Sonarr

on:
  push:
    paths:
      - .github/workflows/sonarr.yml
      - contexts/sonarr/*
  pull_request:
    paths:
      - .github/workflows/sonarr.yml
      - contexts/sonarr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=Sonarr/Sonarr versioning=loose
  SONARR_VERSION: "4.0.13.2932"

jobs:
  versions:
    name: Versions
    outputs:
      SONARR_VERSION: ${{ env.SONARR_VERSION }}
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "SONARR_VERSION=${{ env.SONARR_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        SONARR_VERSION=${{ needs.versions.outputs.SONARR_VERSION }}
      context: contexts/sonarr
      dist-tag: latest
      image-description: Sonarr is an internet PVR for Usenet and Torrents.
      image-name: oliversalzburg/containers/sonarr
      image-tag: v${{ needs.versions.outputs.SONARR_VERSION }}
      image-title: Sonarr
      is-latest: true
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: build-publish
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
