name: ytdl-sub

on:
  push:
    paths:
      - .github/workflows/ytdl-sub.yml
      - contexts/ytdl-sub/*
  pull_request:
    paths:
      - .github/workflows/ytdl-sub.yml
      - contexts/ytdl-sub/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=jmbannon/ytdl-sub versioning=loose
  YTDLSUB_VERSION: "2025.02.05"

jobs:
  versions:
    name: Versions
    outputs:
      YTDLSUB_VERSION: ${{ env.YTDLSUB_VERSION }}
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Generate outputs
        run: |
          echo "YTDLSUB_VERSION=${{ env.YTDLSUB_VERSION }}" >> $GITHUB_OUTPUT

  build-publish:
    name: Call Build
    needs: versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      build-args: |
        YTDLSUB_VERSION=${{ needs.versions.outputs.YTDLSUB_VERSION }}
      context: contexts/ytdl-sub
      image-description: ytdl-sub is a command-line tool that downloads media via yt-dlp and prepares it for your favorite media player (Kodi, Jellyfin, Plex, Emby, modern music players).
      image-name: oliversalzburg/containers/ytdl-sub
      image-tag: ${{ needs.versions.outputs.YTDLSUB_VERSION }}
      image-title: ytdl-sub
      is-latest: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      with-sarif: false
      with-sbom: false

  qa-successful:
    if: ( success() || failure() )
    name: Evaluate QA results
    needs: build-publish
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
